# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名字')),
                ('start', models.DateTimeField(verbose_name='开始')),
                ('end', models.DateTimeField(verbose_name='结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('address', models.TextField(verbose_name='地址')),
            ],
            options={
                'verbose_name': '狼人杀活动',
                'verbose_name_plural': '狼人杀活动',
            },
        ),
    ]
