# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator_avatar',
            field=models.TextField(blank=True, null=True, verbose_name='创建者头像地址'),
        ),
        migrations.AddField(
            model_name='activity',
            name='creator_nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='创建者昵称'),
        ),
        migrations.AddField(
            model_name='activity',
            name='creator_open_id',
            field=models.TextField(blank=True, null=True, verbose_name='创建者微信openID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.TextField(verbose_name='活动地址'),
        ),
    ]
