# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20170612_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='费用'),
        ),
    ]
