# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_open_id', models.TextField(verbose_name='参与者微信OpenID')),
                ('user_avatar', models.TextField(verbose_name='参与者头像')),
                ('user_nickname', models.CharField(max_length=200, verbose_name='参与者昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='留言')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='活动描述'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=15, verbose_name='最大参与人数'),
        ),
        migrations.AddField(
            model_name='participation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='参加的活动', to='activities.Activity'),
        ),
    ]
