# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20170612_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': '活动参与', 'verbose_name_plural': '活动参与'},
        ),
        migrations.AddField(
            model_name='participation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='已付款'),
        ),
    ]
